AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a Glue connection object to an Aurora MySQL DB.

Parameters:
  SubnetId:
    Description: The subnet of the Aurora instance.
    Type: AWS::EC2::Subnet::Id
    Default: subnet-4115c737
  AvailabilityZone:
    Description: The AZ of the Aurora instance.
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-west-2a
  SecurityGroupIdList:
    Description: The list of security groups to apply to the Glue Connection.
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: sg-ca7f99ac
  JDBCConnectionString:
    Type: String
    Default: jdbc:mysql://air-quality.crwizazpv2rg.us-west-2.rds.amazonaws.com:3306/airquality
  ConnectionUser:  
    Type: String
    Default: etl
  ConnectionPassword:  
    Type: String
    Default: abcdefg
    NoEcho: true

Resources:
# Build connection role for access to the RDS instance
  GlueRole: 
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - 
          PolicyName: airquality-s3-policy
          PolicyDocument: 
            Version: 2012-10-17
            Statement: 
              - 
                Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::1s-sagemaker-demos/*
        - PolicyName: airquality-rds-policy
          PolicyDocument: 
            Version: 2012-10-17
            Statement: 
              - 
                Effect: Allow
                Action: "rds:*"
                Resource: arn:aws:rds:us-west-2:842337631775:cluster:air-quality-cluster
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - 
            Effect: Allow
            Principal: 
              Service: 
                - glue.amazonaws.com
            Action: 
              - sts:AssumeRole
      Path: /

  AuroraConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        Description: Connection information for the Aurora instance.
        ConnectionType: JDBC
        # MatchCriteria: airquality
        PhysicalConnectionRequirements:
          AvailabilityZone: !Ref AvailabilityZone
          SecurityGroupIdList: !Ref SecurityGroupIdList
          SubnetId: !Ref SubnetId
        ConnectionProperties: {
          "JDBC_CONNECTION_URL": !Ref JDBCConnectionString,
          "USERNAME": !Ref ConnectionUser,
          "PASSWORD": !Ref ConnectionPassword
        }
        Name: AirQualityDB
  
  UtahSubsetJob:
    Type: AWS::Glue::Job
    Properties:
      Name: UtahSubsetJob
      Role: !Ref GlueRole
      Connections:
        Connections:
          - !Ref AuroraConnection
      MaxRetries: 1
      Description: Subset air quality data to utah entries
      Command: 
        Name: glueetl
        ScriptLocation: s3://1s-sagemaker-demos/scripts/utah_subset.py
      AllocatedCapacity: 2